plugins:
  - jekyll-remote-theme

remote_theme: yakenohara/Jekyll-Simple-Wiki-Theme
repository: yakenohara/VBA-BaseNNumericString

title: Base-N Numeric String
description: 【VBA】N進数の四則演算・基数変換
logo_url: 

show_downloads: true