theme: jekyll-theme-leap-day
show_downloads: true
plugins:
  - jekyll-seo-tag

defaults:
  -
    values:
      title: 【VBA】N進数の四則演算・基数変換
      description: Microsoft Excel 用VBAライブラリ(ユーザー定義関数群)